name: Saludo usando variables y secrets
run-name: ¡Estoy aprendiendo a usar Variables y Secrets!
on:
  workflow_dispatch
env:
  DIA_DE_SEMANA: Miercoles
jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    env:
      SALUDO: Hola
    steps:
      - name: Saludo Variables
        run: echo "$SALUDO, ${{ vars.NOMBRE }}, Hoy es $ {{ env.DIA_DE_SEMANA }}!"

  saludo-secrets:
    runs-on: ubuntu-latest
    env:
      SALUDO: Hola
    steps:
      - name: Saludo secretes
        run: echo "$SALUDO, ${{ vars.NOMBRE }}, tU contraseña es $ {{ env.secrets.PASSWORD }}!"
